#!/usr/bin/env python3
"""Interactive double-exponential-field trapping-profile viewer.

Only double-exponential EF_*, SC_* and TR_* parameters are exposed as sliders.
BM_* and MV_* parameters are read from the config and kept fixed. The data
profile is selected with a profile_index slider.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.widgets import Button, Slider

import trapping_model_RooFit_li as tsim


DEFAULT_CONFIG = Path("SiC_UVLED/configs/RooFit_manual_single_profile_control_doubleExp.json")
DEFAULT_OUTPUT_JSON = Path("SiC_UVLED/configs/RooFit_manual_single_profile_control_doubleExp.json")
DEFAULT_ROOT_DIR = Path("SiC_UVLED/RootFiles")
PROFILE_SIGMA_FRACTION = 0.0175


SLIDER_DEFAULT_RANGES = {
    "EF_BiasVoltage": (-1500.0, 1500.0),
    "EF_ExpAmpLeft": (0.0, 120.0),
    "EF_ExpDecayLeft": (0.2, 250.0),
    "EF_ExpDecayRight": (0.2, 250.0),
    "SC_scaleAmp": (0.1, 3.0),
    "SC_scaleOffset": (-0.25, 0.25),
    "SC_scale_zShift": (-20.0, 20.0),
    "TR_tau_e": (1e-3, 20.0),
    "TR_tau_h": (1e-3, 20.0),
}


SLIDER_NAMES = [
    "profile_index",
    "EF_BiasVoltage",
    "EF_ExpAmpLeft",
    "EF_ExpDecayLeft",
    "EF_ExpDecayRight",
    "SC_scaleAmp",
    "SC_scaleOffset",
    "SC_scale_zShift",
    "TR_tau_e",
    "TR_tau_h",
]


def load_configuration(config_path: Path) -> dict:
    with config_path.open("r", encoding="utf-8") as stream:
        payload = json.load(stream)
    config = payload.get("configuration", payload)
    config = tsim.load_fit_configuration(copy.deepcopy(config))
    for name, spec in config["parameters"].items():
        if not (name.startswith("EF_") or name.startswith("SC_") or name.startswith("TR_")):
            spec["type"] = "fixed"
    config["parameters"]["EF_BiasVoltage"]["enabled"] = True
    config["fit_options"]["field_model"] = "double_exponential"
    config["parameters"]["EF_CoefA"].update({"type": "fixed", "value": 0.0})
    config["parameters"]["EF_CoefB"].update({"type": "fixed", "value": 0.0})
    config["parameters"]["EF_CoefC"].update({"type": "fixed", "value": 0.0})
    config["parameters"]["EF_z0"].update({"type": "fixed", "value": 0.0})
    config["parameters"]["EF_ExpAmpRight"].update({"type": "fixed"})
    return tsim.load_fit_configuration(config)


def load_payload_template(config_path: Path) -> dict:
    with config_path.open("r", encoding="utf-8") as stream:
        payload = json.load(stream)
    if "configuration" not in payload:
        payload = {
            "description": "Interactive RooFit double-exponential profile control generated by interactive_profile_model_sliders_doubleExp.py.",
            "configuration": payload,
        }
    return payload


def json_ready(value):
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(key): json_ready(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_ready(item) for item in value]
    if isinstance(value, float):
        return value if np.isfinite(value) else None
    return value


def initial_profile_index(config_path: Path, rootfiles: list[str]) -> int:
    try:
        payload = json.loads(config_path.read_text())
    except Exception:
        return min(4, max(len(rootfiles) - 1, 0))
    index = int(payload.get("profile_index", min(4, max(len(rootfiles) - 1, 0))))
    return max(0, min(index, len(rootfiles) - 1))


def constant_profile_sigma(profile, fraction=PROFILE_SIGMA_FRACTION):
    profile = np.asarray(profile, dtype=float)
    scale = float(np.nanmax(np.abs(profile)))
    if not np.isfinite(scale) or scale <= 0.0:
        scale = 1.0
    return np.full(profile.shape, fraction * scale, dtype=float)


def slider_limits(name: str, spec: dict) -> tuple[float, float]:
    value = float(spec.get("value", 0.0))
    if "min" in spec and "max" in spec:
        low = float(spec["min"])
        high = float(spec["max"])
    else:
        low, high = SLIDER_DEFAULT_RANGES.get(name, (value - 1.0, value + 1.0))
    if low <= value <= high:
        return low, high
    margin = max(abs(value), 1.0)
    return min(low, value - margin), max(high, value + margin)


def configuration_from_sliders(base_config: dict, sliders: dict[str, Slider]) -> dict:
    config = copy.deepcopy(base_config)
    for name in SLIDER_NAMES:
        if name == "profile_index":
            continue
        if name not in config["parameters"]:
            continue
        config["parameters"][name]["value"] = float(sliders[name].val)
    return tsim.load_fit_configuration(config)


def evaluate_case(base_config, sliders, rootfiles):
    profile_index = int(round(sliders["profile_index"].val))
    profile_index = max(0, min(profile_index, len(rootfiles) - 1))
    xdata, ydata, rootfilename = tsim.get_profileData(profile_index, rootfiles)
    config = configuration_from_sliders(base_config, sliders)
    y_fit, y_fit_e, y_fit_h, y_fit_no_offset, y_fit_offset, response = tsim.simulate_trapping_model(xdata, config)
    parameter_values = tsim._parameter_values(config["parameters"])
    parameter_values = tsim._apply_derived_field_values(parameter_values, config)
    y_sigma = constant_profile_sigma(ydata)
    valid = np.isfinite(y_fit) & np.isfinite(ydata) & np.isfinite(y_sigma) & (y_sigma > 0.0)
    if np.any(valid):
        chi2 = float(np.sum(((y_fit[valid] - ydata[valid]) / y_sigma[valid]) ** 2))
        dof = max(int(np.sum(valid)) - len([n for n in SLIDER_NAMES if n != "profile_index"]), 1)
        chi2_dof = chi2 / dof
    else:
        chi2 = np.nan
        dof = 1
        chi2_dof = np.nan
    return {
        "profile_index": profile_index,
        "rootfilename": rootfilename,
        "configuration": config,
        "parameters": parameter_values,
        "x": xdata,
        "y_data": ydata,
        "y_sigma": y_sigma,
        "y_fit": y_fit,
        "y_fit_e": y_fit_e,
        "y_fit_h": y_fit_h,
        "y_fit_no_offset": y_fit_no_offset,
        "profile_offset": float(y_fit_offset),
        "material_response": response,
        "chi2": chi2,
        "dof": dof,
        "chi2_dof": chi2_dof,
    }


def save_control_json(fallback_template_payload, result, output_json: Path) -> None:
    if output_json.exists():
        with output_json.open("r", encoding="utf-8") as stream:
            payload = json.load(stream)
        if "configuration" not in payload:
            payload = {
                "description": "Interactive RooFit profile control.",
                "configuration": payload,
            }
    else:
        payload = copy.deepcopy(fallback_template_payload)
    payload["description"] = (
        "Interactive RooFit double-exponential profile control. Updated by "
        "interactive_profile_model_sliders_doubleExp.py whenever sliders change."
    )
    payload["profile_index"] = int(result["profile_index"])
    payload["rootfilename"] = str(result["rootfilename"])
    payload["residual_sigma_fraction"] = PROFILE_SIGMA_FRACTION
    payload.setdefault("configuration", {})
    payload["configuration"].setdefault("parameters", {})
    payload["configuration"].setdefault("fit_options", {})
    payload["configuration"]["fit_options"]["field_model"] = "double_exponential"
    for name in SLIDER_NAMES:
        if name == "profile_index":
            continue
        if name in payload["configuration"]["parameters"] and name in result["parameters"]:
            payload["configuration"]["parameters"][name]["value"] = result["parameters"][name]
    payload["configuration"].setdefault("fit_options", {})["relative_sigma_fraction"] = PROFILE_SIGMA_FRACTION
    payload["interactive_state"] = {
        "source_script": "interactive_profile_model_sliders_doubleExp.py",
        "field_model": "double_exponential",
        "chi2": result["chi2"],
        "dof": result["dof"],
        "chi2_dof": result["chi2_dof"],
        "updated_parameters": {
            name: result["parameters"][name]
            for name in SLIDER_NAMES
            if name != "profile_index" and name in result["parameters"]
        },
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    with output_json.open("w", encoding="utf-8") as stream:
        json.dump(json_ready(payload), stream, indent=2, sort_keys=True)
        stream.write("\n")


def safe_plot(axis, x, y, *args, **kwargs):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    if x.shape == y.shape and x.size:
        axis.plot(x, y, *args, **kwargs)


def draw_diagnostics(fig, axes, result):
    axis_profile, axis_residual, axis_field, axis_velocity, axis_response = axes
    for axis in axes:
        axis.clear()

    x = np.asarray(result["x"], dtype=float)
    ydata = np.asarray(result["y_data"], dtype=float)
    yfit = np.asarray(result["y_fit"], dtype=float)
    yfit_e = np.asarray(result["y_fit_e"], dtype=float)
    yfit_h = np.asarray(result["y_fit_h"], dtype=float)
    y_sigma = np.asarray(result["y_sigma"], dtype=float)
    profile_offset = float(result["profile_offset"])
    response = result["material_response"]

    ydata_plot = ydata - profile_offset
    yfit_plot = yfit - profile_offset
    axis_profile.errorbar(
        x,
        ydata_plot,
        yerr=y_sigma,
        fmt="o",
        ms=3,
        color="black",
        ecolor="0.65",
        elinewidth=0.8,
        capsize=0,
        label="data - offset",
    )
    safe_plot(axis_profile, x, yfit_plot, color="tab:orange", lw=2.0, label="model - offset")
    safe_plot(axis_profile, x, yfit_e, color="darkblue", lw=1.4, alpha=0.8, label="e")
    safe_plot(axis_profile, x, yfit_h, color="crimson", lw=1.4, alpha=0.8, label="h")
    axis_profile.set(
        xlabel="focus position z / um",
        ylabel="charge / NE",
        title=(
            f"profile_index={result['profile_index']} | chi2/dof={result['chi2_dof']:.4g} | "
            f"offset={profile_offset:.4g}"
        ),
    )
    axis_profile.legend(frameon=False, fontsize=8)

    if x.shape == yfit_plot.shape:
        residual = ydata_plot - yfit_plot
        axis_residual.errorbar(x, residual, yerr=y_sigma, fmt="o", ms=3, color="black", ecolor="0.65")
    axis_residual.axhline(0.0, color="black", lw=1)
    axis_residual.set(xlabel="focus position z / um", ylabel="data - model / NE", title="residuals")

    z = np.asarray(response.get("z", []), dtype=float)
    safe_plot(axis_velocity, z, response.get("vdrift_mue", []), color="darkblue", label="e")
    safe_plot(axis_velocity, z, response.get("vdrift_muh", []), color="crimson", label="h")
    axis_velocity.set(title="drift velocity", xlabel="z / um", ylabel="velocity / (um/ns)")
    if axis_velocity.get_legend_handles_labels()[0]:
        axis_velocity.legend(frameon=False, fontsize=8)

    safe_plot(axis_response, z, response.get("response_total", []), color="black", label="sum")
    safe_plot(axis_response, z, response.get("response_e", []), color="darkblue", alpha=0.8, label="e")
    safe_plot(axis_response, z, response.get("response_h", []), color="crimson", alpha=0.8, label="h")
    axis_response.set(title="material response", xlabel="z / um", ylabel="response / adim.")
    if axis_response.get_legend_handles_labels()[0]:
        axis_response.legend(frameon=False, fontsize=8)

    safe_plot(axis_field, z, response.get("efield", []), color="tab:green")
    axis_field.axhline(1e-2, color="tab:red", ls="--", lw=0.9)
    axis_field.axhline(0.0, color="0.4", lw=0.8)
    axis_field.set(title="electric field", xlabel="z / um", ylabel="field / (V/um)")

    for axis in axes:
        axis.grid(alpha=0.25)
    root_name = Path(result["rootfilename"]).name
    amp_right = result["parameters"].get("EF_ExpAmpRight", np.nan)
    fig.suptitle(f"{root_name} | derived EF_ExpAmpRight={amp_right:.6g} V/um", fontsize=11)
    fig.canvas.draw_idle()


def main():
    parser = argparse.ArgumentParser(description="Interactive double-exponential-field trapping-profile sliders.")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument(
        "--output-json",
        type=Path,
        default=DEFAULT_OUTPUT_JSON,
        help="JSON updated on every slider change. Default overwrites RooFit_manual_single_profile_control_doubleExp.json.",
    )
    parser.add_argument("--root-dir", type=Path, default=DEFAULT_ROOT_DIR)
    args = parser.parse_args()

    rootfiles = tsim.discover_profile_rootfiles(args.root_dir)
    if not rootfiles:
        raise RuntimeError(f"No ROOT files found under {args.root_dir}")
    template_payload = load_payload_template(args.config)
    base_config = load_configuration(args.config)
    profile_index0 = initial_profile_index(args.config, rootfiles)

    fig = plt.figure(figsize=(13.5, 9.0))
    grid = fig.add_gridspec(3, 3, left=0.07, right=0.97, top=0.88, bottom=0.39, hspace=0.52, wspace=0.35)
    axis_profile = fig.add_subplot(grid[:2, :2])
    axis_residual = fig.add_subplot(grid[2, :2], sharex=axis_profile)
    axis_field = fig.add_subplot(grid[0, 2])
    axis_velocity = fig.add_subplot(grid[1, 2])
    axis_response = fig.add_subplot(grid[2, 2])
    axes = [axis_profile, axis_residual, axis_field, axis_velocity, axis_response]

    sliders = {}
    slider_height = 0.018
    slider_gap = 0.030
    slider_bottom = 0.045
    for idx, name in enumerate(SLIDER_NAMES):
        ypos = slider_bottom + (len(SLIDER_NAMES) - 1 - idx) * slider_gap
        axis = fig.add_axes([0.20, ypos, 0.62, slider_height])
        if name == "profile_index":
            slider = Slider(
                axis,
                name,
                0,
                len(rootfiles) - 1,
                valinit=profile_index0,
                valstep=1,
                valfmt="%0.0f",
                dragging=False,
            )
        else:
            spec = base_config["parameters"][name]
            low, high = slider_limits(name, spec)
            slider = Slider(
                axis,
                name,
                low,
                high,
                valinit=float(spec["value"]),
                valfmt="%.6g",
                dragging=False,
            )
        sliders[name] = slider

    reset_axis = fig.add_axes([0.86, 0.045, 0.09, 0.035])
    reset_button = Button(reset_axis, "Reset")

    status_axis = fig.add_axes([0.84, 0.10, 0.14, 0.21])
    status_axis.axis("off")
    status_text = status_axis.text(0.0, 1.0, "", va="top", family="monospace", fontsize=8)

    def update(_=None):
        try:
            current_config_path = args.output_json if args.output_json.exists() else args.config
            current_config = load_configuration(current_config_path)
            result = evaluate_case(current_config, sliders, rootfiles)
            save_control_json(template_payload, result, args.output_json)
            draw_diagnostics(fig, axes, result)
            params = result["parameters"]
            status_text.set_text(
                "Current values\n"
                f"EF_BiasVoltage={params['EF_BiasVoltage']:.6g}\n"
                f"EF_ExpAmpLeft={params['EF_ExpAmpLeft']:.6g}\n"
                f"EF_ExpDecayLeft={params['EF_ExpDecayLeft']:.6g}\n"
                f"EF_ExpAmpRight={params['EF_ExpAmpRight']:.6g}\n"
                f"EF_ExpDecayRight={params['EF_ExpDecayRight']:.6g}\n"
                f"SC_scaleAmp={params['SC_scaleAmp']:.6g}\n"
                f"SC_scaleOffset={params['SC_scaleOffset']:.6g}\n"
                f"SC_scale_zShift={params['SC_scale_zShift']:.6g}\n"
                f"TR_tau_e={params['TR_tau_e']:.6g}\n"
                f"TR_tau_h={params['TR_tau_h']:.6g}\n"
                f"saved={args.output_json}"
            )
        except Exception as exc:
            status_text.set_text(f"Evaluation failed:\n{exc}")
            fig.canvas.draw_idle()

    def reset(_=None):
        for slider in sliders.values():
            slider.reset()

    for slider in sliders.values():
        slider.on_changed(update)
    reset_button.on_clicked(reset)

    print(f"Loaded config: {args.config}")
    print(f"Loaded {len(rootfiles)} ROOT profiles from {args.root_dir}")
    print(f"Updating JSON on every change: {args.output_json}")
    update()
    plt.show()


if __name__ == "__main__":
    main()
